// Generated by scripts/fetch-feed-seed.js — do not edit manually
// Last updated: 2026-07-20T19:08:24.056Z
// Run: npm run fetch-feed-seed

export const feedSeedCoffees = [
  {
    "id": 120,
    "title": "Vasto",
    "bio": "Café Vasto de Vanguarda do Café! @vanguardadocafe\n\nVariedade: Catuaí 44\nProcesso: Cereja Descascada",
    "origin": "",
    "producer": "Fabio e Helia Protásio",
    "burn": 4,
    "format": 1,
    "tastes": "",
    "views": 4,
    "resized_picture": "https://storage.googleapis.com/thecafe-pictures/coffee/resized/coffee-120-1783709945.jpeg",
    "original_picture": "https://storage.googleapis.com/thecafe-pictures/coffee/original/coffee-120-1783709945.jpeg",
    "user": {
      "id": 2,
      "name": "Alexandre Werneck",
      "username": "xanwerneck",
      "email": "xanwerneck@gmail.com",
      "bio": "Oi, faça parte da comunidade The Cafe e ajude a distribuir os seus conhecimentos sobre café! 😍☕️",
      "verified": true,
      "original_picture": "https://storage.googleapis.com/thecafe-pictures/user/original/user-2-1741743601.png"
    }
  },
  {
    "id": 119,
    "title": "Dengo",
    "bio": "Café 100% Arábica, distribuído pela Dengo, e fabricado pela Unique Cafés Especiais",
    "origin": "",
    "producer": "Unique Cafés Especiais",
    "burn": 5,
    "format": 1,
    "tastes": "",
    "views": 19,
    "resized_picture": "https://storage.googleapis.com/thecafe-pictures/coffee/resized/coffee-119-1781956546.jpg",
    "original_picture": "https://storage.googleapis.com/thecafe-pictures/coffee/original/coffee-119-1781956546.jpg",
    "user": {
      "id": 2,
      "name": "Alexandre Werneck",
      "username": "xanwerneck",
      "email": "xanwerneck@gmail.com",
      "bio": "Oi, faça parte da comunidade The Cafe e ajude a distribuir os seus conhecimentos sobre café! 😍☕️",
      "verified": true,
      "original_picture": "https://storage.googleapis.com/thecafe-pictures/user/original/user-2-1741743601.png"
    }
  },
  {
    "id": 117,
    "title": "Sítio São Sebastião - Bourbon",
    "bio": "",
    "origin": "",
    "producer": "Sítio São Sebastião",
    "burn": 4,
    "format": 1,
    "tastes": "Frutas Amarelas",
    "views": 8,
    "resized_picture": "https://storage.googleapis.com/thecafe-pictures/coffee/resized/coffee-117-1780535986.jpeg",
    "original_picture": "https://storage.googleapis.com/thecafe-pictures/coffee/original/coffee-117-1780535986.jpeg",
    "user": {
      "id": 50,
      "name": "Sítio São Sebastião",
      "username": "sitiosaosebastiao",
      "email": "cafesitiosaosebastiao@gmail.com",
      "bio": null,
      "verified": false,
      "original_picture": null
    }
  },
  {
    "id": 116,
    "title": "Café Jabuticaba 250g",
    "bio": "Todo mês um café escolhido que faz todo sentido estar aqui!\n\nEsse é o Jabuticaba\n\nFoi o terceiro lugar no Concurso do Cerrado Mineiro, na categoria fermentados.\n\nTem notas de berries maduras e jabuticaba em licor, com perfil alcoólico, acidez tartárica pronunciada e doçura prolongada.\n\nProduzido pelo Edson Luiz Inácio, feito para quem gosta de explorar novos caminhos na xícara.\n\n100% arábica.",
    "origin": "Fazenda Canastra - Tapira / MG",
    "producer": "Edson Luiz Ignacio",
    "burn": 5,
    "format": 1,
    "tastes": "javuticaba em licor, berries maduras, alcoolico, acidez tartárica, doçura marcante e prolongada",
    "views": 11,
    "resized_picture": "https://storage.googleapis.com/thecafe-pictures/coffee/resized/coffee-116-1779739020.jpg",
    "original_picture": "https://storage.googleapis.com/thecafe-pictures/coffee/original/coffee-116-1779739020.jpg",
    "user": {
      "id": 49,
      "name": "KOA",
      "username": "koacafes",
      "email": "koacafes@koacafes.com.br",
      "bio": "KŌA - Torrefação de Cafés Especiais",
      "verified": false,
      "original_picture": "https://storage.googleapis.com/thecafe-pictures/user/original/user-49-1779738793.jpg"
    }
  }
];
