// Generated by scripts/fetch-feed-seed.js — do not edit manually
// Last updated: 2026-08-05T01:35:19.388Z
// Run: npm run fetch-feed-seed

export const feedSeedCoffees = [
  {
    "id": 123,
    "title": "Café 85",
    "bio": "O Café 85 é um café original da região das Matas de Minas!\nO Sítio Bom Jardim está localizado a 830-930m de altitude, em Santa Margarida-MG, próximo ao Parque do Seritinga. \nGrãos 100% arábica\n\nOutras características descritas no rótulo:\n- Corpo: Pronunciado\n- Doçura: Elevada\n- Aroma: Frutas amarelas, manga e licor\n- Acidez: Cítrica\n- Sabor: Mel e licor\n- Pontuação Média: 85 pontos",
    "origin": "Santa Margarida - MG",
    "producer": "Ângelo Marcos dos Reis",
    "burn": 5,
    "format": 1,
    "tastes": "Mel e licor",
    "views": 0,
    "resized_picture": "https://storage.googleapis.com/thecafe-pictures/coffee/resized/coffee-123-1785893665.jpeg",
    "original_picture": "https://storage.googleapis.com/thecafe-pictures/coffee/original/coffee-123-1785893665.jpeg",
    "user": {
      "id": 2,
      "name": "Alexandre Werneck",
      "username": "xanwerneck",
      "email": "xanwerneck@gmail.com",
      "bio": "Oi, faça parte da comunidade The Cafe e ajude a distribuir os seus conhecimentos sobre café! 😍☕️",
      "verified": true,
      "original_picture": "https://storage.googleapis.com/thecafe-pictures/user/original/user-2-1741743601.png"
    }
  },
  {
    "id": 122,
    "title": "Patrick Coffees",
    "bio": "Propriedade: Sitio Serra da Boa Esperança\nVariedade: Mundo Novo\nSafra: 2025\nMachado Sul de Minas Gerais\n\nNesse lote de Mundo Novo, trazemos para vocês um café com aroma de mel e notas de chocolate e nozes. Naturalmente doce, esse café foi colhido em Machado-MG a uma altitude superior a 1100 metros. Essa bebida magnífica é reflexo do cuidado que a produtora Augusta Félix e seu filho Afrânio Ananias tem com sua lavoura que produz café há mais de 50 anos.\nDoçura 8\nAcidez 5\nCorpo 8\nAmargor 3",
    "origin": "Machado-MG",
    "producer": "Sitio Serra da Boa Esperança",
    "burn": 4,
    "format": 1,
    "tastes": "aroma de mel e notas de chocolate e nozes",
    "views": 6,
    "resized_picture": "https://storage.googleapis.com/thecafe-pictures/coffee/resized/coffee-122-1784946055.webp",
    "original_picture": "https://storage.googleapis.com/thecafe-pictures/coffee/original/coffee-122-1784946055.webp",
    "user": {
      "id": 2,
      "name": "Alexandre Werneck",
      "username": "xanwerneck",
      "email": "xanwerneck@gmail.com",
      "bio": "Oi, faça parte da comunidade The Cafe e ajude a distribuir os seus conhecimentos sobre café! 😍☕️",
      "verified": true,
      "original_picture": "https://storage.googleapis.com/thecafe-pictures/user/original/user-2-1741743601.png"
    }
  },
  {
    "id": 121,
    "title": "Chiara",
    "bio": "Café de baixa acidez, com um pouco de doçura!\n\nCom a paixão de 3 mulheres, de geração em geração, nosso café ganha vida e se torna único. Chiara, a matriarca, guarda a tradição; Andrea, há mais de 20 anos, cultiva cada grão com dedicação; e Camila torra, para levar o sabor e compartilhar nossa história com o mundo. Na Fazenda Marapé, em Bretejuba, cultivamos mais do que café: cultivamos sonhos e futuros.",
    "origin": "Fazenda Marapé",
    "producer": "Andrea Vivacqua",
    "burn": 4,
    "format": 1,
    "tastes": "Chocolate e Caramelo",
    "views": 7,
    "resized_picture": "https://storage.googleapis.com/thecafe-pictures/coffee/resized/coffee-121-1784940529.jpeg",
    "original_picture": "https://storage.googleapis.com/thecafe-pictures/coffee/original/coffee-121-1784940529.jpeg",
    "user": {
      "id": 2,
      "name": "Alexandre Werneck",
      "username": "xanwerneck",
      "email": "xanwerneck@gmail.com",
      "bio": "Oi, faça parte da comunidade The Cafe e ajude a distribuir os seus conhecimentos sobre café! 😍☕️",
      "verified": true,
      "original_picture": "https://storage.googleapis.com/thecafe-pictures/user/original/user-2-1741743601.png"
    }
  },
  {
    "id": 120,
    "title": "Vasto",
    "bio": "Café Vasto de Vanguarda do Café! @vanguardadocafe\n\nVariedade: Catuaí 44\nProcesso: Cereja Descascada",
    "origin": "",
    "producer": "Fabio e Helia Protásio",
    "burn": 4,
    "format": 1,
    "tastes": "",
    "views": 12,
    "resized_picture": "https://storage.googleapis.com/thecafe-pictures/coffee/resized/coffee-120-1783709945.jpeg",
    "original_picture": "https://storage.googleapis.com/thecafe-pictures/coffee/original/coffee-120-1783709945.jpeg",
    "user": {
      "id": 2,
      "name": "Alexandre Werneck",
      "username": "xanwerneck",
      "email": "xanwerneck@gmail.com",
      "bio": "Oi, faça parte da comunidade The Cafe e ajude a distribuir os seus conhecimentos sobre café! 😍☕️",
      "verified": true,
      "original_picture": "https://storage.googleapis.com/thecafe-pictures/user/original/user-2-1741743601.png"
    }
  }
];
